#!/bin/bash
# MENU DE SELECTION POUR Spotnik-4.0
#
#  F5NLG  27/04/2020
#

while : ; do

MENULIST=(
1 " Restart Spotnik on Stand Alone '95'" \
2 " Restart Spotnik on RRF '96'" \
3 " Restart Spotnik on FON Room '97'" \
4 " Restart Spotnik on TEC Room '98'" \
5 " Restart Spotnik on INT Room '99'" \
6 " Restart Spotnik on BAV Room '100'" \
7 " Restart Spotnik on LOC Room '101'" \
8 " Restart Spotnik on EXP Room '102'" \
9 " Restart Spotnik on EchoLink '103'" \
10 " Restart Spotnik on REG Room '104'" \
11 " Restart Spotnik on Xwindow Digital '105'" \
12 " Restart Spotnik on C4FM/P25/NXDN/DMR '106'" \
13 " See Spotnik working (Logs) 'ctrl c'to leave" \
14 " Configure Wifi or network" \
15 " Trim Sound Alsamixer" \
16 " Edit Svxlink.cfg for all reflectors" \
17 " Edit Svxlink.el for EchoLink." \
18 " Edit ModuleEchoLink.conf" \
19 " Edit Logic.tcl (Dangerous)" \
20 " MC Midnight Commander" \
21 " Configure Dwagent " \
22 " Start / stop RRFRaptor !" \
23 " Enable Numeric mode" \
24 " Disable Numeric mode"
)
# nbre de ligne / colonne / ascenseur ?
choix=$(whiptail --title "- Spotnik 4.0 Menu -"  --menu "                  >> Make your Choice: " 35 60 25 \
"${MENULIST[@]}" \
3>&1 1>&2 2>&3)

exitstatus=$?

#on recupere ce choix
#exitstatus=$?
if [ $exitstatus = 0 ]; then
    echo "Your chosen option:" $choix
else
    echo "You chose Cancel."; break;
fi

# case : action en fonction du choix

case $choix in

1)
/etc/spotnik/restart.default ;;

2)
/etc/spotnik/restart.rrf ;;

3)
/etc/spotnik/restart.fon ;;

4)
/etc/spotnik/restart.tec ;;

5)
/etc/spotnik/restart.int ;;

6)
/etc/spotnik/restart.bav ;;

7)
/etc/spotnik/restart.loc ;;

8)
/etc/spotnik/restart.exp ;;

9)
/etc/spotnik/restart.el ;;

10)
/etc/spotnik/restart.reg ;;

11)
/etc/spotnik/restart.fdv ;;

12)
/etc/spotnik/restart.num ;;

13)
/etc/spotnik/view_svx ;;

14)
nmtui ;;

15)
alsamixer && alsactl store ;;

16)
mcedit /etc/spotnik/svxlink.cfg ;;

17)
mcedit /etc/spotnik/svxlink.el ;;

18)
mcedit /etc/spotnik/svxlink.d/ModuleEchoLink.conf ;;

19)
mcedit /usr/share/svxlink/events.d/local/Logic.tcl ;;

20)
mc /etc/spotnik ;;

21)
sh /usr/share/dwagent/native/configure ;;

22)
sh /opt/RRFRaptor/RRFRaptor.sh ;;

23)
sh ./num.sh enable ;;

24)
sh ./num.sh disable

esac
done
exit 0
